- name: Ensure that minecraft-srv user exists
  ansible.builtin.user:
    name: minecraft-srv
    shell: /bin/bash
    password: '!'
    password_lock: true

- name: Enable lingering for minecraft-srv user
  ansible.builtin.command: loginctl enable-linger minecraft-srv
  changed_when: false

- name: Create user's container systemd directory
  ansible.builtin.file:
    path: /home/minecraft-srv/.config/containers/systemd
    state: directory
    mode: '0755'
    owner: minecraft-srv
    group: minecraft-srv
